name: bioinfo
channels:
  - conda-forge
  - bioconda
dependencies:
  - python=3.11
  - seqkit
  - fastqc=0.12.1
  - multiqc
  - fastp
  - trimmomatic
  - spades
  - quast
  - busco
  - prokka
  - bwa-mem2
  - bowtie2
  - samtools
  - bcftools
  - stacks
  - vcftools
  - entrez-direct
  - sra-tools
  - r-base=4.4.1
  - r-tidyverse
  - r-ggplot2
  - r-vegan
  - r-adegenet
  - r-ape
  - wget
  - curl
  - tree
